name: dafvm
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {json5: ^0.8.0, path: ^1.8.2}
